site_name: Dokumentace Roští.cz
nav:
    - Domů: cs/main.md
    - "Quickstart průvodce":
      - "1. První aplikace": "cs/quickstart/first_app.md"
      - "2. Jednoduchý deployment": cs/quickstart/first_deployment.md
      - "3. Databáze": cs/quickstart/databases.md
      - "4. Nastavení domény": cs/quickstart/domains.md
    - Technologie:
        - Python: cs/apps/python.md
        - PHP: cs/apps/php.md
        - Node.js: cs/apps/nodejs.md
        - Deno: cs/apps/deno.md
        - Ruby: cs/apps/ruby.md
        - Golang: cs/apps/golang.md
    - "Další informace":
        - "Platby za služby": billing.md
        - "Runtime prostředí": runtime.md
        - "Nástroj rosti.sh": rosti_sh.md
        - "Adresářová struktura /srv": srv.md
        - "Správa služeb běžících na pozadí": supervisor.md
        - "Připojení k SSH a databázím z venku": ssh.md
        - "Instalace extra balíčků do systému": extra-packages.md
        - "Cron": cron.md
        - "Memcached a Redis": memcached_redis.md
        - "MongoDB": mongo.md
        - "SMTP server pro odchozí emaily": smtp.md
        - "API": api.md
        - "FAQ": faq.md
theme: readthedocs
markdown_extensions:
  - admonition
