name: Build+Deploy

on: 
  push:
    branches:    
    - "master"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.11' 
    - name: Build
      run: |
        pip3 install mkdocs
        pip3 install pymdown-extensions
        pip3 install mkdocs-mermaid2-plugin
        mkdocs build
    - name: Deploy
      env:
        SSHKEY: ${{ secrets.deploy_ssh_key }}
        HOST: ssh.rosti.cz
        PORT: 13640
      run: |
        echo "$SSHKEY" > ssh.key
        chmod 600 ssh.key
        rsync -avz --delete -e "ssh -i ssh.key -oStrictHostKeyChecking=no -p $PORT" site/ app@$HOST:/srv/app/
