name: Build+Deploy

on: 
  push:
    branches:    
    - "master"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - name: Build
      run: |
        pip3 install mkdocs
        pip3 install pymdown-extensions
        mkdocs build
    - name: Deploy
      env:
        SSHKEY: ${{ secrets.deploy_ssh_key }}
        HOST: ${{ secrets.host }}
        PORT: ${{ secrets.port }}
      run: |
        echo "$SSHKEY" > ssh.key
        chmod 600 ssh.key
        rsync -avz -e "ssh -i ssh.key -oStrictHostKeyChecking=no -p $PORT" site/ app@$HOST:/srv/app/
